# Part 2 — component comparison, screen x surface map, rules, honest gaps.

# Component · WS 2.0 treatment · Our treatment · Surface · Why it sits there · Why it is better · Where WS 2.0 still wins
COMP = [
("The place work lives",
 "A Live Requests table: ID, Request, Status, Progress, Notifications, Owner, Due Date — grouped by month, with search and a filter icon.",
 "A list of rooms, at-risk first, each carrying the exception in plain words and a state badge in ops language (Ratify, Stalled, Verify D+2).",
 "B2 list + context",
 "The list is the only surface a person sees before they know what they are doing. It has to answer 'what needs me' rather than 'what exists'. A table answers the second question well and the first one badly, because every row looks equally important.",
 "A row states the exception and the SOP, not a status word: 'Tariq silent 4h - SOP-15 says offer onward'. You can triage without opening anything.",
 "Above roughly a dozen rows a table wins on scanning. We built a board for SWAT and reverted it - see the Honest gaps tab."),
("Request detail",
 "A detail pane beside the list: request ID, deliver-to, CC, instructions, input and reference files, requested delivery, entity, charge code, with an Edit link opening a modal.",
 "The request is a room. Its facts arrive as cards in the stream; its structure is summoned as spaces over the same ground.",
 "B4 conversation + B3 spaces",
 "The vision doc's whole distinction is what is ground and what is summoned. In Framework B the room is the ground, so a request cannot be a document you visit - it is a place you are in, and its detail is pulled in on demand.",
 "Reading a fact and acting on it are the same gesture. In WS 2.0 the detail pane is read-only and every action is a separate modal.",
 "A modal that shows all fields at once is faster to audit than cards you summon one at a time."),
("Request → assignment → activity",
 "Implied by indentation on the Gantt (ASM- rows under REQ-), plus a Flowchart view. Two views of the same thing, neither of them the navigation.",
 "The tree IS the navigation: a request opens to its assignments, an assignment to its activities, and every node is a room with its own conversation.",
 "B2 list + context",
 "This is the only object EZ actually manages, and the vision doc says each node is a room. Putting the hierarchy in the list means the structure and the navigation are the same thing, so there is nothing to keep in sync.",
 "Two taps deep, nothing rendered until asked for. Each level is addressable, so a conversation attaches to the node it is about - which is what makes a dispute filable against an activity rather than a request.",
 "-"),
("The plan against time",
 "A first-class Gantt: hour-level columns, a 12-hour zoom control, tier and assignment filters, per-row start and due, assignee, and a Today marker.",
 "A plan space summoned into the room, showing the activities on one axis with today marked and the dependencies that are not yours greyed.",
 "B3 spaces",
 "A Gantt is a scheduling instrument, not a reading surface. Summoning it keeps the room readable when you do not need it and gives it the full width when you do.",
 "The performer's version shows what their bar gates - Sana cannot start until this lands - which is the only reason a performer needs a Gantt at all.",
 "WS 2.0's is better: zoomable, filterable, hour-level. Ours is a strip. For a desk running forty requests theirs is the stronger tool."),
("The splitter",
 "A Plan / Splitter toggle on the request. The mechanism that turns one file into parts and parts into activities.",
 "A splitter space: cut into 2, 3, 4 or 6, preview the ranges and the cost per part, remainder to part one, apply and the activities are written into the tree.",
 "B3 spaces",
 "Every number downstream comes from here - the unit count, the price, the payout. It belongs beside the tree it writes into, not in a separate mode.",
 "The preview states the arithmetic before it commits, including where the remainder goes, so the split is auditable at the moment it is made rather than in a log afterwards.",
 "-"),
("Editing the plan",
 "Modal forms: Create/Edit Assignment (offering, language, template, urgency, unit type and count, entity, charge code, invoice code) and Create/Edit Activity (skill, units, start, deadline, estimated vs committed, input files with tool and access, required outputs with mandatory and map-to, allocation with rating and availability).",
 "Per-node menus on the tree - edit, add activity, add sibling or nested assignment, pause, duplicate, cancel - opening the same field set as a card in the room.",
 "B3 spaces + popover",
 "Editing belongs where the thing being edited is visible. A modal hides the tree you are reasoning about; a card in the room keeps it above you.",
 "The consequence updates live: cancel a 700 activity and the margin moves 50% to 63% while you decide. WS 2.0 shows you the result after you save.",
 "WS 2.0's field coverage is still ahead at request level, and its menus include a Timeline Manager we have no answer to."),
("Alerts and attention",
 "Notification count badges on each request row, and a bell.",
 "A bar under the room header carrying that room's top alert with the action on it; a sheet listing everything, grouped into Needs you, For your awareness, and Handled.",
 "B6 ambient AI",
 "An alert is about a node, so it belongs on the node. Home is the only place that sees everything - anywhere else, an alert from elsewhere is noise.",
 "The bar carries the resolving action, so an alert is cleared where it happened rather than navigated to. A badge tells you a number; this tells you the move.",
 "-"),
("Decisions",
 "Modals with Confirm and Cancel.",
 "Decision cards in the stream: a coloured spine by severity, the consequence in prose, and the actions on the card itself.",
 "B4 conversation",
 "A decision has a before and an after, and both belong in the record. A modal has neither - it appears from nowhere and leaves no trace.",
 "The card states what happens if you do nothing, which is the information a modal never carries. It also stays in the room afterwards as the reason the thing happened.",
 "-"),
("Conversation",
 "A Chats side panel, scoped by Request / Assignments / Experts, with unread dots and file attachments.",
 "The conversation is the ground the whole app stands on. Every other surface is summoned over it.",
 "B4 conversation",
 "This is Framework B's founding choice and the vision doc's one distinction that drives everything: the room is the ground; structure is summoned.",
 "Nothing has to be kept in sync between a record and a discussion about the record, because they are the same stream. WS 2.0 already had chat - it was simply beside the work rather than under it.",
 "Their panel is honest about scale: an unread list of rooms is easier to work than a stream when you hold forty of them."),
("Knowing who hears you",
 "Implicit in which chat you opened.",
 "A scope chip on the prompt naming the audience and its visibility - the owner sees it, SWAT means the owner sees it too, a peer means neither, AI means nobody.",
 "B5 prompt",
 "Ambiguity about audience is the single biggest failure mode of a chat-first product. If people are unsure who hears them, they either overshare across a boundary or stop using it.",
 "Visibility is stated per option at the moment of choosing, not inferred from which panel you happen to be in.",
 "-"),
("A private word with a peer",
 "None. Everything is on the record.",
 "A private strand inside the activity, lilac and locked, headed with who can and cannot see it - and promotable into the room in one action.",
 "B5 prompt + B4",
 "The question an expert most needs to ask is the one they cannot ask on the record. Denying it does not prevent it; it moves it to WhatsApp where EZ can neither help nor learn from it.",
 "Private by content, never secret in existence, and escalatable. A side-channel you can promote beats one you have to hide.",
 "-"),
("Files",
 "A Files panel: Input Files and Reference Files, each downloadable.",
 "Three shelves - source, working, deliverable - with a progress bar on each file and the boundary rule stated between them.",
 "B3 spaces",
 "Files are where a request actually stalls. Shelving them by which side of the boundary they sit on makes the rule visible instead of remembered.",
 "Per-file progress answers which file is holding the request up, not which assignment. And the deliverable shelf shows what cannot cross yet, and why.",
 "-"),
("Deliveries",
 "A Deliveries panel with real versioning - V1 and V2, each with notes, files, Download All and a share link.",
 "A deliveries space with the same versioning, plus the QA notes carried onto the version that answers them.",
 "B3 spaces",
 "Versions are a record, and a record belongs with the object rather than in a modal.",
 "Parity, with the QA round-trip attached: v2 carries what changed and why, so the client sees the argument, not just the file.",
 "WS 2.0 got here first and its panel is complete. This is a straight copy of a good idea."),
("Verify and settlement",
 "None as a surface. WS 2.0 auto-invoices synchronously on mark-complete, and a repair cron later fixes requests that skipped V&S.",
 "Verify is a full-width ledger: every billable line with its reconciliation pre-computed, per-line and bulk verify, and the invoice raised from the table.",
 "Full pane",
 "This is the commercial gate. It is a table because it is worked down, not discussed - the one place in the app where a conversation would be in the way.",
 "The PRD names the auto-invoice-on-complete behaviour as the single most important thing to change. One tap emits one billable event; the invoice and the performer payout fire off it together. There is no cron to repair drift because there is no drift.",
 "-"),
("Money, client side",
 "Not seen in the shared screens.",
 "Money owns its pane: wallet, work history, statements, budget tracker - with credits stated as the funding source and terms as the fallback.",
 "B2 list + B4",
 "Money is a different question from work, so it takes the whole pane rather than sitting as one more room among requests.",
 "The tracker projects the month at the current pace, which is the number a client actually asks for. Prepaid credits and 14-day terms are reconciled explicitly so the same work never appears to be billed twice.",
 "-"),
("Money, expert side",
 "Not seen.",
 "Earnings line by line as units times rate, payouts by period, the rate card, and the rule that payout follows verified work regardless of whether the client has paid.",
 "B2 list + B4",
 "An expert's money question is 'what am I owed and when', which has nothing to do with the client's receivables.",
 "It is theirs. An earlier build showed the client's overdue invoices to the expert, which is both a boundary breach and useless to them.",
 "-"),
("Money, SWAT side",
 "Not seen.",
 "Both books: receivables, client wallets, payouts, tracker, with in/out filters and the net position stated.",
 "B2 list + B4",
 "SWAT is the only role that sees both ends, which is also why the margin only exists on their surface.",
 "The wallet state gates intake, so money and work are connected rather than parallel.",
 "-"),
("Who is on this",
 "A Collaborators panel grouping avatars by Requestors, Owners and Experts.",
 "A face stack in the room header opening a sheet grouped by role, with presence and a message action on each.",
 "Room header + popover",
 "Knowing your audience is a precondition for writing anything, so it belongs in the header rather than a panel you remember to open.",
 "One tap from the room to a message with the right person. WS 2.0 shows you who they are; ours also gets you to them.",
 "-"),
("What changed",
 "An Edit Logs panel: the change, the timestamp, the user, and the device and IP it came from.",
 "An edit log space, written by the app as changes happen, with the same attribution.",
 "B3 spaces",
 "This is the evidence layer. It has to be reachable from the object under dispute, which means it lives with the object.",
 "Parity on content. The difference is that the expert also has one, so a unit-count dispute has two symmetrical records rather than one that only ops can see.",
 "WS 2.0 shipped this first and it is genuinely well done. We copied it."),
("Intake",
 "Requests appear in the list. No queue for unmapped or ambiguous senders in the screens shared.",
 "An intake room: unmapped senders held as decision cards with the AI's confidence and the alternatives, and the request created only on a human's tap.",
 "B4 conversation",
 "Intake is a queue of decisions, and a decision belongs in a stream where its resolution is recorded.",
 "Nothing auto-attaches to the wrong client, and the reason a mapping was chosen survives in the room.",
 "-"),
("Creating a request",
 "A Create New Request modal with the full field set, then Create Assignment, then Create Activity - three modals to a working plan.",
 "Two roads from one card: let the composer draft it, or build the plan by hand from the skeleton the graph requires.",
 "B4 conversation + B3",
 "Most briefs are ordinary and want a draft in seconds; a few are odd enough that a draft is only something to undo. Forcing either road on both is what makes the other one painful.",
 "The composed road produces a ratifiable plan in one step rather than three modals. The by-hand road starts from a valid skeleton - one assignment and its mandatory Deliver - so an invalid plan is harder to build than a valid one.",
 "-"),
("Progress",
 "A percentage on the request row and a segmented bar per assignment.",
 "Progress in units at activity level, rolled up per assignment and per request, and separately per file.",
 "B3 spaces + B2",
 "Percentages are derived; units are the fact. Reporting the derived number invites the argument.",
 "The performer sets units and the percentage follows, so nobody is asked to estimate a percentage. Per-file progress then answers which file is the blocker.",
 "-"),
("Retainers and periods",
 "Not seen.",
 "A retainer is a room with a service period, its committed hours, and a period-close verify - the same tree as anything else.",
 "B2 list + B4",
 "One engine. A retainer differs only in what 'complete' means, and the UI should show that rather than special-case it.",
 "Type B work exists in the same surfaces as Type A instead of needing its own product.",
 "-"),
("An agent as a performer",
 "Tools tiles on the home screen - Translate.ai, Flip.ai, Read.ai, Consult.ai - launched as apps.",
 "The agent is allocated like a person and has a room; it simply does not accept, it runs, and a human QA follows.",
 "B2 list + B4",
 "If an agent is a performer in the graph it should be a performer in the UI, or the model and the interface disagree.",
 "Agent and human work appear in the same tree and the same verify ledger, so an agent-first request is not a separate flow.",
 "WS 2.0's tiles make the agents discoverable in a way ours does not - a person browsing has no idea what agents exist."),
("Rules at the point of need",
 "Not seen.",
 "SOPs and playbooks in a drawer beside the conversation, and the relevant rule quoted on the card that needs it.",
 "Right rail",
 "A rule you have to remember is a rule that gets broken. Reference sits beside the work rather than in it, because it is read, not acted on.",
 "The escalation card cites SOP-15 by name, so the policy and the action are the same object.",
 "-"),
("Capacity",
 "Not seen.",
 "A capacity space for SWAT and a utilisation space for the expert, both stated as committed hours against quota.",
 "B3 spaces",
 "Allocation without capacity is guessing, and the person being allocated has a right to see the same number.",
 "Both sides see the same figure, which is what makes an offer arguable rather than imposed.",
 "-"),
("List lifecycle",
 "Live / Drafts / Delivered / Archived as request states, with month grouping.",
 "Verify closes a room and retires it to an archive; the record and the conversation stay searchable.",
 "B2 list",
 "A room is an open loop rather than a place. When the loop shuts there is nothing left to say, so it should stop taking up attention.",
 "The list empties as you work rather than growing until it is abandoned.",
 "WS 2.0's four explicit states are clearer than our two, and Drafts exists there and barely here."),
("Keeping a line in view",
 "Not seen.",
 "Pin any message - a card, someone else's line, or your own - to the top of its room.",
 "B4 conversation",
 "A long room buries the one line that matters, and which line that is only the person in it can know.",
 "It works on any message rather than a blessed subset, because the app cannot know what is load-bearing for you.",
 "-"),
("Search",
 "Per-list search plus a filter control.",
 "One search across rooms, people, money and archived work.",
 "B2 list",
 "If the list is scoped by tab, search must not be - otherwise you have to know where a thing is before you can look for it.",
 "Archived rooms stay findable, so closing a loop never loses the record.",
 "-"),
("Bulk work",
 "Select All with Cancel, Pause, Delete and Duplicate across activities.",
 "Not built.",
 "-",
 "-",
 "-",
 "WS 2.0 wins outright. At forty rows bulk is the difference between a tool and a chore."),
]

# Screens x Framework B surfaces — the vision doc's own format
SCREENS = [
("Client","Home / workspace","Home active","Rooms, at-risk first; money as a rail item","Morning brief tiles, plan, my requests","The workspace agent stream","Ask or act; scope = workspace","Ranked decisions in the stream"),
("Client","Request room","Requests active","This request selected; its assignments beneath","Scope sheet, files, deliverables, instructions","The request stream, both sides of the boundary","Message; scope = request; boundary internal or client-visible","Plan proposed, date at risk, delivery ready"),
("Client","Delivery & verify","Requests active","The delivered request","Deliverables with versions and downloads","Verify card in the stream","Verify, flag an issue, request a revision","Nothing bills until you verify"),
("Client","Money","Money active","Wallet, work history, statements, tracker","The open money section","Money agent stream","Ask about a bill; run a command","Overdue, expiring credits, budget pace"),
("Client","Retainer","Requests active","The engagement, its periods beneath","Usage against commitment","Period stream","Message; scope = engagement","Period closes in 9 days"),
("Expert","Home / my work","Home active","Pinned SWAT, then the tree of what she holds","My work table, utilisation, the plan","The workspace stream","Ask or act; scope = workspace","Offer, unit change, QA fail"),
("Expert","Activity room","My work active","The activity, under its assignment and request","Brief, plan, files, deliveries, log","The activity stream, private strands inline","Message; scope = owner / desk / peer / AI","This will not clear 18:00"),
("Expert","Offer","My work active","The offered activity","The brief, before accepting","Offer card with why-you and the clock","Ask before accepting","Re-proposes to Priya in 2h 39m"),
("Expert","Earnings","Money active","Earnings, payouts, rate card","The open money section","Money stream","Ask about a line or a payout","Released, pending verify"),
("Expert","Archive","My work active","Closed rooms, collapsed to a count","-","The room as it was, read-only","Disabled, with the reason","-"),
("SWAT","Home / the floor","Home active","Rooms at-risk first; intake pinned","Floor brief, the floor list, upcoming","The workspace stream","Ask or act; scope = the floor","6 need your hand"),
("SWAT","Intake queue","Requests active","The queue, pinned","-","Unmapped senders and raise-a-request as cards","Message; scope = intake","91% Nimbus - map or reject"),
("SWAT","Request room","Requests active","Request, its assignments and activities beneath","Tree, plan, splitter, files, edit log","The request stream, client boundary visible","Message; scope = team / client / AI","Ratify, stalled, verify pending"),
("SWAT","Assignment room","Requests active","The assignment, its activities beneath","Tree, files, log","The assignment stream","Message; scope = assignment","-"),
("SWAT","Activity room","Requests active","The activity","Tree, files, log","The activity stream","Message; scope = activity","-"),
("SWAT","Verify","Verify active","Hidden - the table takes the pane","-","Replaced by the ledger","Hidden","Nothing bills before the tap"),
("SWAT","Money","Money active","Receivables, wallets, payouts, tracker","The open money section","Money stream","Ask about a book","Wallet below floor blocks intake"),
("SWAT","Client room","Clients active","The client and its requests","Client instructions","The client stream, everything client-visible","Message; scope = client","Disputed a line"),
("SWAT","People / capacity","Team active","People and agents","Capacity","The person stream","Message; scope = person","Over capacity"),
]

RULES = [
("R-01","AI proposes, a human ratifies","Nothing becomes an assignment without a human tap. No auto-start anywhere.","PRD E6/E7, FR-7.1"),
("R-02","Verify is the only commercial trigger","Nothing bills before the tap. One billable event fans out to invoice and payout together.","PRD E10/E11, FR-11.1, the D4 fix"),
("R-03","A performer is paid off verified work","Independent of whether the client has paid. A client dispute never claws back a verified payout.","PRD FR-11.2, E13 F5"),
("R-04","The client never sees who does the work","Not the expert, not the sub-vendor. Milestones, never machinery.","PRD E14, boundary rules"),
("R-05","Roles attach per node, not per user","One person can be the performer on an activity and the owner of the assignment above it. Access is computed per node.","PRD S2, added 9 Aug"),
("R-06","Deliver is the mandatory last activity","Every assignment has one, minted automatically. It cannot be the thing you cancel.","PRD E7, work graph"),
("R-07","Wallet: deduct at create, settle at verify, refund on cancel","Prepaid work is funded by credits; work beyond them falls to terms.","PRD FR-11.4"),
("R-08","A funded wallet is an intake precondition","Publishing work that cannot be paid for is a false start. Negative balance is per-tenant config.","PRD E11 edge cases"),
("R-09","Rework is not new scope","A QA round-trip adds no units and claws nothing back.","PRD E9, FR-9.5"),
("R-10","A fix is free, an addition is priced","Stated before the client chooses, not after.","PRD E13 F1"),
("R-11","Reassignment fee-split; the workspace never funds the overrun","An EZ rule expressed as config.","PRD E13 F2"),
("R-12","Cancel refunds, pause suspends billing","Both are terminal or paused states the UI must show.","PRD E13 F3"),
("R-13","Goodwill fixes are a new linked assignment","Never a reopening; the original billing is untouched.","PRD E13 F4"),
("R-14","Escalate before the breach, never after","T-4h on a date at risk. The UI should make that the easy path.","SOP-12"),
("R-15","Units are the fact; the percentage is derived","Nobody is asked to estimate a percentage.","Design rule, this build"),
("R-16","Every audience states its own visibility","The prompt says who hears it before you send.","Design rule, this build"),
("R-17","A room is an open loop","Verify closes it; the record stays searchable.","Design rule, 9 Aug"),
("R-18","Files are pointers, bytes live in the enclave","Brokered access with JIT credentials and expiry.","PRD FR-11.8, security.md"),
]

GAPS = [
("Scanning at volume","WS 2.0 wins","Their Live Requests table beats a chat list above roughly a dozen rows. We built a floor board for SWAT on 9 Aug and reverted it the same day at the user's call. The honest position is that this is unresolved, not solved.","Open"),
("Bulk operations","WS 2.0 wins","Select All with Cancel / Pause / Delete / Duplicate. We have none. At forty rows this is the difference between a tool and a chore.","Not built"),
("The Gantt","WS 2.0 wins","Hour-level columns, a zoom control and tier filters. Ours is a strip with a today marker.","Partial"),
("Request lifecycle states","WS 2.0 wins","Live / Drafts / Delivered / Archived. We have Draft and an archive, and no month grouping.","Partial"),
("Allocation UI","WS 2.0 wins","Their Create Activity shows the candidate, their rating and their availability at the moment of choosing. We show none of it - the biggest single gap on the SWAT side.","Not built"),
("Timeline Manager","WS 2.0 only","On their request menu. We have no equivalent and have not established what it does.","Unknown"),
("Agent discoverability","WS 2.0 wins","Tools tiles on their home screen make the agents browsable. Ours only appear where already allocated.","Not built"),
("Ambient AI vs chat-first","Tension with the PRD","PRD S3 says 'Ambient AI, not a chatbot - AI appears inline as suggestions a human approves, never a separate assistant to converse with.' Every app we have built has a workspace agent you talk to. This is a deliberate departure and needs explicit sign-off rather than being discovered later.","Needs a decision"),
("Cascade and invariants","Our bug","Cancelling an assignment leaves its activities live and its cost in the margin. Pausing does not cascade. The mandatory Deliver can be cancelled. Reproduced 9 Aug; fix parked.","Known, parked"),
("Room lifecycle exits","Our gap","Verify is the only way a room closes. Cancel, pause, a declined offer and reassignment all leave a dead room behind.","Known, parked"),
("Intake edge cases","Gap on both","Ambiguous sender disambiguation, email dedupe, and flagging a missing or past deadline before composing. Neither product does these.","Not built"),
("Expert availability","Gap on both","Availability is a Pass-1 hard filter in allocation and neither product lets an expert set it.","Not built"),
("Feedback reaching the performer","Gap on both","WS 2.0 captures a rating; nothing shows it to the person who earned it. We show it to SWAT only.","Partial"),
("Outcome / BOT billing","Gap on both","Needs Joy's formula before it can have a UI.","Blocked"),
("Dispute inbox","Our gap","The expert app raises unit disputes and timeline recommendations. Nothing in SWAT receives either. Asked for 7 Aug, still open.","Not built"),
]
